# Auto-generated by llm_harness_codegen.py
# model=gpt-5.4
# api_mode=responses
# source_yaml=/root/yaml/tf.quantization.fake_quant_with_min_max_vars_per_channel.yaml
# source_api_txt=/root/tf_api_txt/tf_quantization_fake_quant_with_min_max_vars_per_channel.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=1

import atheris
import tensorflow as tf
import sys
import math
import numpy as np

def _consume_small_dim(fdp):
    choices = [1, 2, 3, 4, 5, 8]
    return choices[fdp.ConsumeIntInRange(0, len(choices) - 1)]


def _consume_shape(fdp):
    # +++ 修改：rank 从 0 开始，允许生成标量 +++
    rank = fdp.ConsumeIntInRange(0, 4)
    if rank == 0:
        return []      # 标量，不消耗任何维度数据
    c = _consume_small_dim(fdp)
    if rank == 1:
        return [c]
    if rank == 2:
        return [_consume_small_dim(fdp), c]
    if rank == 3:
        return [_consume_small_dim(fdp), _consume_small_dim(fdp), c]
    return [_consume_small_dim(fdp), _consume_small_dim(fdp), _consume_small_dim(fdp), c]


def _sanitize_float(x):
    if not math.isfinite(x):
        return 0.0
    if x > 1e6:
        return 1e6
    if x < -1e6:
        return -1e6
    return x


def _consume_float_list(fdp, n):
    vals = []
    for _ in range(n):
        if fdp.ConsumeBool():
            v = fdp.ConsumeFloat()
        else:
            v = float(fdp.ConsumeIntInRange(-1024, 1024))
        vals.append(_sanitize_float(v))
    return vals


def _make_input_tensor(fdp, shape):
    count = 1
    for d in shape:
        count *= d

    if fdp.ConsumeBool():
        values = _consume_float_list(fdp, count)
    else:
        base_choices = [-10.0, -6.0, -1.0, -0.0, 0.0, 1e-6, 0.5, 1.0, 6.0, 10.0, 127.0, 255.0]
        values = [base_choices[fdp.ConsumeIntInRange(0, len(base_choices) - 1)] for _ in range(count)]

    # 注意：当 shape=[] 时，count 为 1（空 shape 的乘积为 1），tf.constant 会生成标量
    return tf.constant(values, dtype=tf.float32, shape=shape)


def _make_min_max_tensors(fdp, channels):
    # +++ 注意：channels 现在由外部随机决定，不再依赖 inputs.shape[-1] +++
    strategy = fdp.ConsumeIntInRange(0, 5)
    mins = []
    maxs = []

    for _ in range(channels):
        if strategy == 0:
            lo = float(fdp.ConsumeIntInRange(-20, 0))
            hi = float(fdp.ConsumeIntInRange(0, 20))
        elif strategy == 1:
            center = _sanitize_float(fdp.ConsumeFloat())
            span = abs(_sanitize_float(fdp.ConsumeFloat())) + 1e-3
            lo = center - span
            hi = center + span
        elif strategy == 2:
            lo = -6.0
            hi = 6.0
        elif strategy == 3:
            lo = -1.0
            hi = 1.0
        elif strategy == 4:
            lo = 0.0
            hi = 0.0 if fdp.ConsumeBool() else 6.0
        else:
            lo = float(fdp.ConsumeIntInRange(-5, 5))
            hi = lo if fdp.ConsumeBool() else lo + abs(float(fdp.ConsumeIntInRange(0, 10)))

        lo = _sanitize_float(lo)
        hi = _sanitize_float(hi)
        if lo > hi:
            lo, hi = hi, lo

        mins.append(lo)
        maxs.append(hi)

    return tf.constant(mins, dtype=tf.float32), tf.constant(maxs, dtype=tf.float32)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        shape = _consume_shape(fdp)
        inputs = _make_input_tensor(fdp, shape)

        # +++ 修改：随机确定 min/max 的通道数，而不是依赖 shape[-1] +++
        # 50% 概率使用 shape[-1]（当 shape 非空），50% 概率随机生成（1~8）
        if fdp.ConsumeBool() and len(shape) > 0:
            channels = shape[-1]
        else:
            channels = fdp.ConsumeIntInRange(1, 8)  # 可以为 1，正好命中 PoC

        min_tensor, max_tensor = _make_min_max_tensors(fdp, channels)

        num_bits_candidates = [-1, 0, 1, 2, 4, 7, 8, 16, 31, 32, 64, 128, None]  # 加了 None 和更多极端值
        idx = fdp.ConsumeIntInRange(0, len(num_bits_candidates) - 1)
        num_bits = num_bits_candidates[idx]
        if num_bits is None:
            # 不传 num_bits，使用默认值
            result = tf.quantization.fake_quant_with_min_max_vars_per_channel(
                inputs=inputs,
                min=min_tensor,
                max=max_tensor,
                narrow_range=fdp.ConsumeBool(),
            )
        else:
            narrow_range = fdp.ConsumeBool()
            result = tf.quantization.fake_quant_with_min_max_vars_per_channel(
                inputs=inputs,
                min=min_tensor,
                max=max_tensor,
                num_bits=num_bits,
                narrow_range=narrow_range,
            )

        if fdp.ConsumeBool():
            # 同样将 raw_ops 版本也覆盖
            if num_bits is None:
                tf.raw_ops.FakeQuantWithMinMaxVarsPerChannel(
                    inputs=inputs,
                    min=min_tensor,
                    max=max_tensor,
                    narrow_range=fdp.ConsumeBool(),
                )
            else:
                tf.raw_ops.FakeQuantWithMinMaxVarsPerChannel(
                    inputs=inputs,
                    min=min_tensor,
                    max=max_tensor,
                    num_bits=num_bits,
                    narrow_range=fdp.ConsumeBool(),
                )

        if fdp.ConsumeBool():
            _ = tf.shape(result)
        if fdp.ConsumeBool():
            _ = tf.reduce_sum(result)
        if fdp.ConsumeBool():
            _ = tf.reduce_min(result)
        if fdp.ConsumeBool():
            _ = tf.reduce_max(result)
        if fdp.ConsumeBool():
            _ = result.numpy()

    except (
        tf.errors.InvalidArgumentError,
        tf.errors.UnimplementedError,
        tf.errors.InternalError,
        tf.errors.ResourceExhaustedError,
        ValueError,
        TypeError,
        RuntimeError,
        AssertionError,
        IndexError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()