# Auto-generated by llm_harness_codegen.py
# model=gpt-5.4
# api_mode=responses
# source_yaml=/root/yaml_list_2/08_final/tf.math.reduce_min.yaml
# source_api_txt=/root/tf_api_txt/tf_math_reduce_min.txt
# source_atheris_doc=//root/atheris-doc/atheris_readme.txt
# repair_attempts_used=1

import atheris

# with atheris.instrument_imports():
import sys
import numpy as np
import tensorflow as tf


_NUMERIC_DTYPES = [
    tf.float16,
    tf.float32,
    tf.float64,
    tf.bfloat16,
    tf.int8,
    tf.int16,
    tf.int32,
    tf.int64,
    tf.uint8,
    tf.uint16,
    tf.uint32,
    tf.uint64,
]

_AXIS_DTYPES = [tf.int32, tf.int64]


def _consume_shape(fdp, rank):
    shape = []
    max_total = 256
    total = 1
    for _ in range(rank):
        dim = fdp.ConsumeIntInRange(1, 16)
        if total * dim > max_total:
            dim = max(1, max_total // max(1, total))
        shape.append(dim)
        total *= dim
    return shape


def _num_elements(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _consume_tensor_values(fdp, dtype, count):
    if dtype in (tf.float16, tf.float32, tf.float64, tf.bfloat16):
        vals = []
        mode = fdp.ConsumeIntInRange(0, 5)
        special = [-np.inf, -1.0, -0.0, 0.0, 1.0, np.inf, np.nan]
        for _ in range(count):
            if mode == 0:
                vals.append(float(fdp.ConsumeIntInRange(-8, 8)))
            elif mode == 1:
                vals.append(fdp.ConsumeFloat())
            elif mode == 2:
                vals.append(fdp.ConsumeFloatInRange(-1e3, 1e3))
            elif mode == 3:
                vals.append(0.0)
            elif mode == 4:
                vals.append(special[fdp.ConsumeIntInRange(0, len(special) - 1)])
            else:
                vals.append(float(fdp.ConsumeIntInRange(-1, 1)))
        return vals

    if dtype in (tf.int8, tf.int16, tf.int32, tf.int64):
        lo, hi = {
            tf.int8: (-128, 127),
            tf.int16: (-32768, 32767),
            tf.int32: (-2**31, 2**31 - 1),
            tf.int64: (-2**31, 2**31 - 1),
        }[dtype]
        edge = [lo, -1, 0, 1, hi]
        vals = []
        use_edge = fdp.ConsumeBool()
        for _ in range(count):
            if use_edge and fdp.ConsumeBool():
                vals.append(edge[fdp.ConsumeIntInRange(0, len(edge) - 1)])
            else:
                vals.append(fdp.ConsumeIntInRange(lo, hi))
        return vals

    if dtype in (tf.uint8, tf.uint16, tf.uint32, tf.uint64):
        hi = {
            tf.uint8: 255,
            tf.uint16: 65535,
            tf.uint32: 2**32 - 1,
            tf.uint64: 2**32 - 1,
        }[dtype]
        edge = [0, 1, min(255, hi), hi]
        vals = []
        use_edge = fdp.ConsumeBool()
        for _ in range(count):
            if use_edge and fdp.ConsumeBool():
                vals.append(edge[fdp.ConsumeIntInRange(0, len(edge) - 1)])
            else:
                vals.append(fdp.ConsumeIntInRange(0, hi))
        return vals

    return [0] * count


def _make_tensor(fdp):
    dtype = _NUMERIC_DTYPES[fdp.ConsumeIntInRange(0, len(_NUMERIC_DTYPES) - 1)]
    rank = fdp.ConsumeIntInRange(1, 4)
    shape = _consume_shape(fdp, rank)
    count = _num_elements(shape)
    values = _consume_tensor_values(fdp, dtype, count)
    arr = np.array(values).reshape(shape)
    if dtype == tf.bfloat16:
        return tf.cast(tf.constant(arr, dtype=tf.float32), tf.bfloat16)
    return tf.constant(arr, dtype=dtype)


def _normalize_unique_axes(candidates, rank):
    seen = set()
    out = []
    for axis in candidates:
        norm = axis % rank
        if norm not in seen:
            seen.add(norm)
            out.append(axis)
    return out


def _make_axis(fdp, rank):
    if fdp.ConsumeBool():
        return None

    axis_dtype = _AXIS_DTYPES[fdp.ConsumeIntInRange(0, len(_AXIS_DTYPES) - 1)]
    mode = fdp.ConsumeIntInRange(0, 6)

    if mode == 0:
        return fdp.ConsumeIntInRange(-rank, rank - 1)

    if mode == 1:
        target_len = fdp.ConsumeIntInRange(0, rank)
        pool = list(range(-rank, rank))
        axes = []
        while pool and len(axes) < target_len:
            idx = fdp.ConsumeIntInRange(0, len(pool) - 1)
            axes.append(pool.pop(idx))
        return _normalize_unique_axes(axes, rank)

    if mode == 2:
        target_len = fdp.ConsumeIntInRange(0, rank)
        axes = []
        for _ in range(target_len):
            axes.append(fdp.ConsumeIntInRange(-rank, rank - 1))
        return tuple(_normalize_unique_axes(axes, rank))

    if mode == 3:
        target_len = fdp.ConsumeIntInRange(0, rank)
        axes = []
        for _ in range(target_len):
            axes.append(fdp.ConsumeIntInRange(-rank, rank - 1))
        axes = _normalize_unique_axes(axes, rank)
        return tf.constant(axes, dtype=axis_dtype)

    if mode == 4:
        return tf.constant([], dtype=axis_dtype)

    if mode == 5:
        return []

    return tuple(range(rank))


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        input_tensor = _make_tensor(fdp)
        rank = len(input_tensor.shape)
        axis = _make_axis(fdp, rank)
        keepdims = fdp.ConsumeBool()

        if fdp.ConsumeBool():
            result = tf.math.reduce_min(input_tensor, axis=axis, keepdims=keepdims)
        else:
            if axis is None:
                reduction_indices = list(range(rank))
            else:
                reduction_indices = axis
            result = tf.raw_ops.Min(
                input=input_tensor,
                reduction_indices=reduction_indices,
                keep_dims=keepdims,
            )

        _ = tf.convert_to_tensor(result)
        _ = result.shape
        try:
            _ = result.numpy()
        except (
            tf.errors.InvalidArgumentError,
            tf.errors.UnimplementedError,
            tf.errors.InternalError,
            tf.errors.ResourceExhaustedError,
            ValueError,
            TypeError,
            RuntimeError,
            AssertionError,
            IndexError,
            NotImplementedError,
        ):
            return
        except Exception:
            return

    except (
        tf.errors.InvalidArgumentError,
        tf.errors.UnimplementedError,
        tf.errors.InternalError,
        tf.errors.ResourceExhaustedError,
        ValueError,
        TypeError,
        RuntimeError,
        AssertionError,
        IndexError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
