# Auto-generated by llm_harness_codegen.py
# model=gpt-5.4
# api_mode=responses
# source_yaml=/root/yaml_list_4/08_final/tf.signal.fft.yaml
# source_api_txt=/root/tf_api_txt/tf_signal_fft.txt
# source_atheris_doc=//root/atheris-doc/atheris_readme.txt
# repair_attempts_used=1

import atheris

# with atheris.instrument_imports():
import sys
import numpy as np
import tensorflow as tf


def _consume_dtype(fdp):
    return tf.complex64 if fdp.ConsumeBool() else tf.complex128


def _consume_dim(fdp, is_last):
    if is_last:
        choice = fdp.ConsumeIntInRange(0, 7)
        if choice == 0:
            return 1
        if choice == 1:
            return 2
        if choice == 2:
            return 3
        if choice == 3:
            return 4
        if choice == 4:
            return 8
        if choice == 5:
            return 16
        if choice == 6:
            return 32
        return fdp.ConsumeIntInRange(1, 64)
    return fdp.ConsumeIntInRange(1, 6)


def _consume_shape(fdp):
    rank = fdp.ConsumeIntInRange(1, 4)
    shape = []
    for i in range(rank):
        shape.append(_consume_dim(fdp, i == rank - 1))
    return shape


def _consume_scalar_float(fdp):
    choice = fdp.ConsumeIntInRange(0, 11)
    if choice == 0:
        return 0.0
    if choice == 1:
        return 1.0
    if choice == 2:
        return -1.0
    if choice == 3:
        return 0.5
    if choice == 4:
        return -0.5
    if choice == 5:
        return 1e-6
    if choice == 6:
        return -1e-6
    if choice == 7:
        return 1e3
    if choice == 8:
        return -1e3
    if choice == 9:
        return np.pi
    if choice == 10:
        return -np.pi
    return fdp.ConsumeFloat()


def _make_complex_tensor(fdp, shape, dtype):
    count = 1
    for d in shape:
        count *= d

    strategy = fdp.ConsumeIntInRange(0, 6)

    if strategy == 0:
        real = np.zeros(count, dtype=np.float64)
        imag = np.zeros(count, dtype=np.float64)
    elif strategy == 1:
        val_r = _consume_scalar_float(fdp)
        val_i = _consume_scalar_float(fdp)
        real = np.full(count, val_r, dtype=np.float64)
        imag = np.full(count, val_i, dtype=np.float64)
    elif strategy == 2:
        seq = np.arange(count, dtype=np.float64)
        real = seq
        imag = -seq
    elif strategy == 3:
        seq = np.linspace(-1.0, 1.0, num=count, dtype=np.float64)
        real = seq
        imag = seq[::-1]
    elif strategy == 4:
        idx = np.arange(count, dtype=np.float64)
        real = np.sin(idx)
        imag = np.cos(idx)
    elif strategy == 5:
        byte_count = min(max(count * 16, 1), 4096)
        raw = fdp.ConsumeBytes(byte_count)
        arr = np.frombuffer(raw, dtype=np.uint8).astype(np.float64)
        needed = count * 2
        if arr.size == 0:
            arr = np.zeros(needed, dtype=np.float64)
        arr = np.resize(arr, needed)
        arr = (arr - 128.0) / 16.0
        real = arr[:count]
        imag = arr[count:count * 2]
    else:
        real = np.empty(count, dtype=np.float64)
        imag = np.empty(count, dtype=np.float64)
        for i in range(count):
            real[i] = _consume_scalar_float(fdp)
            imag[i] = _consume_scalar_float(fdp)

    complex_arr = (real + 1j * imag).reshape(shape)
    np_dtype = np.complex64 if dtype == tf.complex64 else np.complex128
    complex_arr = complex_arr.astype(np_dtype, copy=False)
    return tf.convert_to_tensor(complex_arr, dtype=dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _consume_dtype(fdp)
        shape = _consume_shape(fdp)
        input_tensor = _make_complex_tensor(fdp, shape, dtype)

        if fdp.ConsumeBool():
            result = tf.signal.fft(input_tensor)
        else:
            result = tf.raw_ops.FFT(input=input_tensor)

        if fdp.ConsumeBool():
            _ = tf.math.real(result)
        if fdp.ConsumeBool():
            _ = tf.math.imag(result)
        if fdp.ConsumeBool():
            _ = tf.math.abs(result)
        if fdp.ConsumeBool():
            _ = tf.signal.ifft(result)
        if fdp.ConsumeBool():
            _ = tf.shape(result)
        if fdp.ConsumeBool():
            _ = result.numpy()

    except (
        tf.errors.InvalidArgumentError,
        tf.errors.UnimplementedError,
        tf.errors.InternalError,
        tf.errors.ResourceExhaustedError,
        ValueError,
        TypeError,
        RuntimeError,
        AssertionError,
        IndexError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
