# Auto-generated by llm_harness_codegen.py
# model=gpt-5.4
# api_mode=responses
# source_yaml=/root/yaml_list_3/08_final/tf.nn.conv2d.yaml
# source_api_txt=/root/tf_api_txt/tf_nn_conv2d.txt
# source_atheris_doc=//root/atheris-doc/atheris_readme.txt
# repair_attempts_used=1

import atheris

# with atheris.instrument_imports():
import sys
import numpy as np
import tensorflow as tf


def _choice(fdp, seq):
    return seq[fdp.ConsumeIntInRange(0, len(seq) - 1)]


def _dtype_choice(fdp):
    return _choice(fdp, [tf.float16, tf.bfloat16, tf.float32, tf.float64])


def _small_dim(fdp, lo, hi):
    return fdp.ConsumeIntInRange(lo, hi)


def _safe_float(fdp):
    if fdp.ConsumeBool():
        return float(fdp.ConsumeIntInRange(-16, 16))
    v = fdp.ConsumeFloat()
    if not np.isfinite(v):
        return 0.0
    if v > 1e4:
        return 1e4
    if v < -1e4:
        return -1e4
    return float(v)


def _tensor_values(fdp, dtype, size):
    vals = [_safe_float(fdp) for _ in range(size)]
    if dtype == tf.float16:
        return np.asarray(vals, dtype=np.float16)
    if dtype == tf.bfloat16:
        return np.asarray(vals, dtype=np.float32)
    if dtype == tf.float32:
        return np.asarray(vals, dtype=np.float32)
    if dtype == tf.float64:
        return np.asarray(vals, dtype=np.float64)
    raise TypeError("Unsupported dtype")


def _make_tensor(fdp, shape, dtype):
    size = 1
    for d in shape:
        size *= int(d)
    arr = _tensor_values(fdp, dtype, size).reshape(shape)
    return tf.constant(arr, dtype=dtype)


def _expand_hw(value, data_format):
    if isinstance(value, int):
        if data_format == "NHWC":
            return [1, value, value, 1]
        return [1, 1, value, value]
    if len(value) == 2:
        if data_format == "NHWC":
            return [1, value[0], value[1], 1]
        return [1, 1, value[0], value[1]]
    if len(value) == 4:
        return list(value)
    raise ValueError("Unsupported strides/dilations shape")


def _make_stride_or_dilation(fdp, data_format, force_valid_edges=True):
    mode = fdp.ConsumeIntInRange(0, 2)
    a = fdp.ConsumeIntInRange(1, 4)
    b = fdp.ConsumeIntInRange(1, 4)
    if mode == 0:
        raw = a
    elif mode == 1:
        raw = [a, b]
    else:
        if data_format == "NHWC":
            raw = [1, a, b, 1]
        else:
            raw = [1, 1, a, b]
    expanded = _expand_hw(raw, data_format)
    if force_valid_edges:
        if data_format == "NHWC":
            expanded[0] = 1
            expanded[3] = 1
        else:
            expanded[0] = 1
            expanded[1] = 1
    return raw, expanded


def _make_explicit_padding(fdp, data_format):
    pads = [fdp.ConsumeIntInRange(0, 4) for _ in range(4)]
    if data_format == "NHWC":
        nested = [[0, 0], [pads[0], pads[1]], [pads[2], pads[3]], [0, 0]]
    else:
        nested = [[0, 0], [0, 0], [pads[0], pads[1]], [pads[2], pads[3]]]
    flat = [x for pair in nested for x in pair]
    return nested, flat


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _dtype_choice(fdp)
        data_format = _choice(fdp, ["NHWC", "NCHW"])
        padding_mode = _choice(fdp, ["SAME", "VALID", "EXPLICIT"])

        batch_rank_extra = fdp.ConsumeIntInRange(0, 1)
        batch_prefix = [_small_dim(fdp, 1, 3) for _ in range(batch_rank_extra)]

        n = _small_dim(fdp, 1, 3)
        h = _small_dim(fdp, 1, 8)
        w = _small_dim(fdp, 1, 8)
        c_in = _small_dim(fdp, 1, 6)
        c_out = _small_dim(fdp, 1, 6)

        k_h = _small_dim(fdp, 1, 5)
        k_w = _small_dim(fdp, 1, 5)

        if data_format == "NHWC":
            input_shape = batch_prefix + [n, h, w, c_in] if batch_rank_extra else [n, h, w, c_in]
        else:
            input_shape = batch_prefix + [n, c_in, h, w] if batch_rank_extra else [n, c_in, h, w]

        filter_shape = [k_h, k_w, c_in, c_out]

        input_tensor = _make_tensor(fdp, input_shape, dtype)
        filter_tensor = _make_tensor(fdp, filter_shape, dtype)

        strides_raw, strides_4 = _make_stride_or_dilation(fdp, data_format, force_valid_edges=True)
        dilations_raw, dilations_4 = _make_stride_or_dilation(fdp, data_format, force_valid_edges=True)

        if padding_mode == "EXPLICIT":
            padding_nested, explicit_paddings = _make_explicit_padding(fdp, data_format)
            padding_arg = padding_nested
        else:
            explicit_paddings = []
            padding_arg = padding_mode

        result = tf.nn.conv2d(
            input=input_tensor,
            filters=filter_tensor,
            strides=strides_raw,
            padding=padding_arg,
            data_format=data_format,
            dilations=dilations_raw,
            name="atheris_conv2d",
        )

        if fdp.ConsumeBool():
            raw_input = input_tensor
            if len(input_shape) > 4:
                if data_format == "NHWC":
                    merged_n = 1
                    for d in input_shape[:-3]:
                        merged_n *= d
                    raw_shape = [merged_n] + input_shape[-3:]
                else:
                    merged_n = 1
                    for d in input_shape[:-4]:
                        merged_n *= d
                    raw_shape = [merged_n] + input_shape[-3:]
                raw_input = tf.reshape(input_tensor, raw_shape)

            _ = tf.raw_ops.Conv2D(
                input=raw_input,
                filter=filter_tensor,
                strides=strides_4,
                padding=padding_mode if padding_mode != "EXPLICIT" else "EXPLICIT",
                use_cudnn_on_gpu=fdp.ConsumeBool(),
                explicit_paddings=explicit_paddings,
                data_format=data_format,
                dilations=dilations_4,
            )

        if fdp.ConsumeBool():
            _ = tf.identity(result)
            _ = tf.shape(result)
            _ = tf.reduce_sum(result)

    except (
        tf.errors.InvalidArgumentError,
        tf.errors.UnimplementedError,
        tf.errors.InternalError,
        tf.errors.ResourceExhaustedError,
        ValueError,
        TypeError,
        RuntimeError,
        AssertionError,
        IndexError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
