# Auto-generated by llm_harness_codegen.py
# model=gpt-5.4
# api_mode=responses
# source_yaml=/root/yaml_list_3/08_final/tf.nn.avg_pool2d.yaml
# source_api_txt=/root/tf_api_txt/tf_nn_avg_pool2d.txt
# source_atheris_doc=//root/atheris-doc/atheris_readme.txt
# repair_attempts_used=1

import atheris

# with atheris.instrument_imports():
import sys
import math
import tensorflow as tf


def _consume_dtype(fdp):
    dtypes = [tf.float16, tf.bfloat16, tf.float32, tf.float64]
    return dtypes[fdp.ConsumeIntInRange(0, len(dtypes) - 1)]


def _consume_shape(fdp, data_format):
    n = fdp.ConsumeIntInRange(1, 4)
    h = fdp.ConsumeIntInRange(1, 8)
    w = fdp.ConsumeIntInRange(1, 8)
    c = fdp.ConsumeIntInRange(1, 8)
    if data_format == "NHWC":
        return [n, h, w, c]
    return [n, c, h, w]


def _consume_float_values(fdp, count):
    special = [
        0.0,
        1.0,
        -1.0,
        0.5,
        -0.5,
        1e-6,
        -1e-6,
        65504.0,
        -65504.0,
        3.4028235e38,
        -3.4028235e38,
        float("inf"),
        float("-inf"),
        float("nan"),
    ]
    out = []
    for _ in range(count):
        mode = fdp.ConsumeIntInRange(0, 3)
        if mode == 0:
            out.append(float(fdp.ConsumeIntInRange(-16, 16)))
        elif mode == 1:
            out.append(special[fdp.ConsumeIntInRange(0, len(special) - 1)])
        elif mode == 2:
            out.append(fdp.ConsumeFloat())
        else:
            sign = -1.0 if fdp.ConsumeBool() else 1.0
            numerator = fdp.ConsumeIntInRange(0, 1000)
            denominator = fdp.ConsumeIntInRange(1, 1000)
            out.append(sign * (numerator / denominator))
    return out


def _make_tensor(fdp, shape, dtype):
    numel = 1
    for dim in shape:
        numel *= dim
    values = _consume_float_values(fdp, numel)
    tensor = tf.constant(values, dtype=dtype)
    return tf.reshape(tensor, shape)


def _expand_param(param, data_format):
    if isinstance(param, int):
        if data_format == "NHWC":
            return [1, param, param, 1]
        return [1, 1, param, param]
    if isinstance(param, (list, tuple)):
        if len(param) == 1:
            return _expand_param(int(param[0]), data_format)
        if len(param) == 2:
            if data_format == "NHWC":
                return [1, int(param[0]), int(param[1]), 1]
            return [1, 1, int(param[0]), int(param[1])]
        if len(param) == 4:
            return [int(x) for x in param]
    raise ValueError("Invalid pooling parameter")


def _consume_pool_param(fdp, data_format):
    mode = fdp.ConsumeIntInRange(0, 2)
    a = fdp.ConsumeIntInRange(1, 4)
    b = fdp.ConsumeIntInRange(1, 4)
    batch_dim = 1 if fdp.ConsumeBool() else fdp.ConsumeIntInRange(1, 4)
    channel_dim = 1 if fdp.ConsumeBool() else fdp.ConsumeIntInRange(1, 4)

    if mode == 0:
        return fdp.ConsumeIntInRange(1, 4)
    if mode == 1:
        if fdp.ConsumeBool():
            return [a]
        return [a, b]
    if data_format == "NHWC":
        return [batch_dim, a, b, channel_dim]
    return [batch_dim, channel_dim, a, b]


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        data_format = ["NHWC", "NCHW"][fdp.ConsumeIntInRange(0, 1)]
        dtype = _consume_dtype(fdp)
        shape = _consume_shape(fdp, data_format)
        value = _make_tensor(fdp, shape, dtype)

        ksize = _consume_pool_param(fdp, data_format)
        strides = _consume_pool_param(fdp, data_format)
        padding = ["SAME", "VALID"][fdp.ConsumeIntInRange(0, 1)]

        if fdp.ConsumeBool():
            result = tf.nn.avg_pool2d(
                input=value,
                ksize=ksize,
                strides=strides,
                padding=padding,
                data_format=data_format,
                name=None,
            )
        else:
            result = tf.nn.avg_pool2d(
                value,
                ksize=ksize,
                strides=strides,
                padding=padding,
                data_format=data_format,
            )

        if fdp.ConsumeBool():
            raw_ksize = _expand_param(ksize, data_format)
            raw_strides = _expand_param(strides, data_format)
            raw_result = tf.raw_ops.AvgPool(
                value=value,
                ksize=raw_ksize,
                strides=raw_strides,
                padding=padding,
                data_format=data_format,
            )
            _ = raw_result.shape

        if fdp.ConsumeBool():
            _ = tf.shape(result)
        else:
            _ = result.numpy()

        if fdp.ConsumeBool():
            _ = tf.math.reduce_sum(result)
        if fdp.ConsumeBool():
            _ = tf.math.reduce_mean(result)
        if fdp.ConsumeBool() and tf.size(result) > 0:
            _ = tf.math.is_finite(result)

    except (
        tf.errors.InvalidArgumentError,
        tf.errors.UnimplementedError,
        tf.errors.InternalError,
        tf.errors.ResourceExhaustedError,
        ValueError,
        TypeError,
        RuntimeError,
        AssertionError,
        IndexError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
